In [1]:
# отключаем предупреждения Anaconda
import warnings
warnings.simplefilter('ignore')

# импортируем необходимые библиотеки
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
plt.rc('font', family='Verdana')

# Считывание CSV-файла в объект DataFrame

In [2]:
# записываем CSV-файл в объект DataFrame
data = pd.read_csv("C:/data/credit.csv", encoding='cp1251', sep=';')

In [3]:
# смотрим форму датафрейма
data.shape

(170746, 15)

In [4]:
# выводим первые 5 наблюдений датафрейма
data.head()

,client_id,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,monthly_income,credit_count,overdue_credit_count,open_account_flg
0,1,M,48.0,MAR,UMN,59998,10,28,"0,770249",GRD,КРАСНОДАРСКИЙ КРАЙ,30000.0,1.0,1.0,0
1,2,F,28.0,MAR,UMN,10889,6,2,"0,248514",GRD,МОСКВА,43000.0,2.0,0.0,0
2,3,M,32.0,MAR,SPC,10728,12,2,"0,459589",SCH,САРАТОВСКАЯ ОБЛАСТЬ,23000.0,5.0,0.0,0
3,4,F,27.0,DIV,SPC,"12009,09",12,2,"0,362536",GRD,ВОЛГОГРАДСКАЯ ОБЛАСТЬ,17000.0,2.0,0.0,0
4,5,M,45.0,MAR,SPC,"16908,89",10,2,"0,421385",SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,25000.0,1.0,0.0,0

In [5]:
# удаляем переменную client_id
del data['client_id']

# Преобразование типов переменных

In [6]:
# смотрим типы переменных
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170746 entries, 0 to 170745
Data columns (total 14 columns):
gender                  170746 non-null object
age                     170744 non-null float64
marital_status          170744 non-null object
job_position            170746 non-null object
credit_sum              170745 non-null object
credit_month            170746 non-null int64
tariff_id               170746 non-null int64
score_shk               170743 non-null object
education               170743 non-null object
living_region           170554 non-null object
monthly_income          170745 non-null float64
credit_count            161516 non-null float64
overdue_credit_count    161516 non-null float64
open_account_flg        170746 non-null int64
dtypes: float64(4), int64(3), object(7)
memory usage: 18.2+ MB
None

In [7]:
# преобразуем указанные переменные в тип object
for i in ['gender', 'marital_status', 'job_position', 'education', 
          'tariff_id', 'living_region', 'okrug', 'open_account_flg']:
    if i in data.columns:
        data[i]=data[i].astype('object')

In [8]:
# в указанных переменных заменяем запятые на точки и
# преобразуем в тип float
for i in ['credit_sum', 'score_shk']:
    if i in data.columns:
        data[i]=data[i].str.replace(',', '.').astype('float')

In [9]:
# смотрим типы переменных
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170746 entries, 0 to 170745
Data columns (total 14 columns):
gender                  170746 non-null object
age                     170744 non-null float64
marital_status          170744 non-null object
job_position            170746 non-null object
credit_sum              170745 non-null float64
credit_month            170746 non-null int64
tariff_id               170746 non-null object
score_shk               170743 non-null float64
education               170743 non-null object
living_region           170554 non-null object
monthly_income          170745 non-null float64
credit_count            161516 non-null float64
overdue_credit_count    161516 non-null float64
open_account_flg        170746 non-null object
dtypes: float64(6), int64(1), object(7)
memory usage: 18.2+ MB
None

In [10]:
# выводим первые 5 наблюдений датафрейма
data.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,monthly_income,credit_count,overdue_credit_count,open_account_flg
0,M,48.0,MAR,UMN,59998.00,10,28,0.770249,GRD,КРАСНОДАРСКИЙ КРАЙ,30000.0,1.0,1.0,0
1,F,28.0,MAR,UMN,10889.00,6,2,0.248514,GRD,МОСКВА,43000.0,2.0,0.0,0
2,M,32.0,MAR,SPC,10728.00,12,2,0.459589,SCH,САРАТОВСКАЯ ОБЛАСТЬ,23000.0,5.0,0.0,0
3,F,27.0,DIV,SPC,12009.09,12,2,0.362536,GRD,ВОЛГОГРАДСКАЯ ОБЛАСТЬ,17000.0,2.0,0.0,0
4,M,45.0,MAR,SPC,16908.89,10,2,0.421385,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,25000.0,1.0,0.0,0

# Переименование категорий переменных

In [11]:
# создаем словарь, в котором ключем является старое
# название категории, значением – новое название
# категории
d = {'M':'Male', 'F':'Female'}

# передаем словарь в метод map
data['gender'] = data['gender'].map(d)
data.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,monthly_income,credit_count,overdue_credit_count,open_account_flg
0,Male,48.0,MAR,UMN,59998.00,10,28,0.770249,GRD,КРАСНОДАРСКИЙ КРАЙ,30000.0,1.0,1.0,0
1,Female,28.0,MAR,UMN,10889.00,6,2,0.248514,GRD,МОСКВА,43000.0,2.0,0.0,0
2,Male,32.0,MAR,SPC,10728.00,12,2,0.459589,SCH,САРАТОВСКАЯ ОБЛАСТЬ,23000.0,5.0,0.0,0
3,Female,27.0,DIV,SPC,12009.09,12,2,0.362536,GRD,ВОЛГОГРАДСКАЯ ОБЛАСТЬ,17000.0,2.0,0.0,0
4,Male,45.0,MAR,SPC,16908.89,10,2,0.421385,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,25000.0,1.0,0.0,0

In [12]:
# создаем словарь, в котором ключем является старое
# название категории, значением – новое название
# категории
f = {'Male':'M', 'Female':'F'}

# передаем в метод replace словарь, в котором ключем
# будет название переменной, а значением - словарь со
# старыми и новыми названиями категорий
data = data.replace({'gender': f})
data.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,monthly_income,credit_count,overdue_credit_count,open_account_flg
0,M,48.0,MAR,UMN,59998.00,10,28,0.770249,GRD,КРАСНОДАРСКИЙ КРАЙ,30000.0,1.0,1.0,0
1,F,28.0,MAR,UMN,10889.00,6,2,0.248514,GRD,МОСКВА,43000.0,2.0,0.0,0
2,M,32.0,MAR,SPC,10728.00,12,2,0.459589,SCH,САРАТОВСКАЯ ОБЛАСТЬ,23000.0,5.0,0.0,0
3,F,27.0,DIV,SPC,12009.09,12,2,0.362536,GRD,ВОЛГОГРАДСКАЯ ОБЛАСТЬ,17000.0,2.0,0.0,0
4,M,45.0,MAR,SPC,16908.89,10,2,0.421385,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,25000.0,1.0,0.0,0

# Обработка редких категорий

In [13]:
# выводим частоты категорий по каждой
# категориальной переменной
categorical_columns = [c for c in data.columns if data[c].dtype.name == 'object']
for c in categorical_columns:
    print(data[c].value_counts())

F    88697
M    82049
Name: gender, dtype: int64
MAR    93955
UNM    52148
DIV    16970
CIV     4196
WID     3475
Name: marital_status, dtype: int64
SPC    134680
UMN     17674
BIS      5591
PNA      4107
DIR      3750
ATP      2791
WRK       656
NOR       537
WOI       352
INP       241
BIU       126
WRP       110
PNI        65
PNV        40
PNS        12
HSK         8
INV         5
ONB         1
Name: job_position, dtype: int64
2     69355
28    39117
19    15537
20    10970
25     7497
30     5538
22     3930
18     3339
3      3232
1      2245
23     2228
6      2102
29     1007
8       766
4       717
9       579
7       540
32      414
10      376
11      370
31      317
12      303
21      132
13       56
5        36
14       11
16       10
26        7
15        6
24        5
27        2
33        1
17        1
Name: tariff_id, dtype: int64
SCH    87536
GRD    72594
UGR     9941
PGR      565
ACD      107
Name: education, dtype: int64
МОСКОВСКАЯ ОБЛАСТЬ                     12844
МОСКВА                                  9261
ТЮМЕНСКАЯ ОБЛАСТЬ                       8735
КРАСНОДАРСКИЙ КРАЙ                      8355
САНКТ-ПЕТЕРБУРГ                         8303
РЕСПУБЛИКА ТАТАРСТАН                    7667
СВЕРДЛОВСКАЯ ОБЛАСТЬ                    7316
РЕСПУБЛИКА БАШКОРТОСТАН                 6466
ЧЕЛЯБИНСКАЯ ОБЛАСТЬ                     5155
САМАРСКАЯ ОБЛАСТЬ                       5104
СТАВРОПОЛЬСКИЙ КРАЙ                     4617
РОСТОВСКАЯ ОБЛАСТЬ                      4328
ИРКУТСКАЯ ОБЛАСТЬ                       4323
НИЖЕГОРОДСКАЯ ОБЛАСТЬ                   3695
ПЕРМСКИЙ КРАЙ                           3614
ЛЕНИНГРАДСКАЯ ОБЛАСТЬ                   3529
КРАСНОЯРСКИЙ КРАЙ                       3121
КЕМЕРОВСКАЯ ОБЛАСТЬ                     2890
АСТРАХАНСКАЯ ОБЛАСТЬ                    2719
ВОЛОГОДСКАЯ ОБЛАСТЬ                     2605
ВОЛГОГРАДСКАЯ ОБЛАСТЬ                   2293
САРАТОВСКАЯ ОБЛАСТЬ                     2282
НОВОСИБИРСКАЯ ОБЛАСТЬ                   2169
АРХАНГЕЛЬСКАЯ ОБЛАСТЬ                   1895
РЕСПУБЛИКА КОМИ                         1860
РЕСПУБЛИКА САХА (ЯКУТИЯ)                1857
ВОРОНЕЖСКАЯ ОБЛАСТЬ                     1723
РЕСПУБЛИКА БУРЯТИЯ                      1643
ХАБАРОВСКИЙ КРАЙ                        1560
ТВЕРСКАЯ ОБЛАСТЬ                        1548
                                       ...
БЕЛГОРОДСКАЯ ОБЛАСТЬ                     750
ОРЛОВСКАЯ ОБЛАСТЬ                        748
НОВГОРОДСКАЯ ОБЛАСТЬ                     745
РЯЗАНСКАЯ ОБЛАСТЬ                        728
КАЛИНИНГРАДСКАЯ ОБЛАСТЬ                  728
РЕСПУБЛИКА МОРДОВИЯ                      717
САХАЛИНСКАЯ ОБЛАСТЬ                      705
РЕСПУБЛИКА МАРИЙ ЭЛ                      700
РЕСПУБЛИКА КАРЕЛИЯ                       679
КИРОВСКАЯ ОБЛАСТЬ                        647
КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА          637
ТОМСКАЯ ОБЛАСТЬ                          626
КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСПУБЛИКА          576
ПСКОВСКАЯ ОБЛАСТЬ                        575
РЕСПУБЛИКА ТЫВА                          564
РЕСПУБЛИКА АДЫГЕЯ                        554
АЛТАЙСКИЙ КРАЙ                           553
КОСТРОМСКАЯ ОБЛАСТЬ                      514
РЕСПУБЛИКА ХАКАСИЯ                       480
КАМЧАТСКИЙ КРАЙ                          412
РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ      379
РЕСПУБЛИКА КАЛМЫКИЯ                      305
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ             203
МАГАДАНСКАЯ ОБЛАСТЬ                      159
РЕСПУБЛИКА ДАГЕСТАН                       69
РЕСПУБЛИКА АЛТАЙ                          54
ЧУКОТСКИЙ АВТОНОМНЫЙ ОКРУГ                32
ЧЕЧЕНСКАЯ РЕСПУБЛИКА                      31
РЕСПУБЛИКА ИНГУШЕТИЯ                      19
ЧИТИНСКАЯ ОБЛАСТЬ                         17
Name: living_region, Length: 81, dtype: int64
0    140690
1     30056
Name: open_account_flg, dtype: int64

In [14]:
# выводим частоты категорий для переменной job_position,
# dropna=False выведет частоту пропусков, если они есть 
print(data['job_position'].value_counts(dropna=False))

SPC    134680
UMN     17674
BIS      5591
PNA      4107
DIR      3750
ATP      2791
WRK       656
NOR       537
WOI       352
INP       241
BIU       126
WRP       110
PNI        65
PNV        40
PNS        12
HSK         8
INV         5
ONB         1
Name: job_position, dtype: int64

In [15]:
# записываем указанные категории переменной
# job_position в отдельную категорию OTHER
data.at[data['job_position'] == 'PNV', 'job_position'] = 'OTHER'
data.at[data['job_position'] == 'PNS', 'job_position'] = 'OTHER'
data.at[data['job_position'] == 'HSK', 'job_position'] = 'OTHER'
data.at[data['job_position'] == 'INV', 'job_position'] = 'OTHER'
data.at[data['job_position'] == 'ONB', 'job_position'] = 'OTHER'

In [16]:
# выводим частоты категорий для переменной job_position
print(data['job_position'].value_counts(dropna=False))

SPC      134680
UMN       17674
BIS        5591
PNA        4107
DIR        3750
ATP        2791
WRK         656
NOR         537
WOI         352
INP         241
BIU         126
WRP         110
OTHER        66
PNI          65
Name: job_position, dtype: int64

In [17]:
# выводим частоты категорий для переменной tariff_id
print(data['tariff_id'].value_counts(dropna=False))

2     69355
28    39117
19    15537
20    10970
25     7497
30     5538
22     3930
18     3339
3      3232
1      2245
23     2228
6      2102
29     1007
8       766
4       717
9       579
7       540
32      414
10      376
11      370
31      317
12      303
21      132
13       56
5        36
14       11
16       10
26        7
15        6
24        5
27        2
33        1
17        1
Name: tariff_id, dtype: int64

In [18]:
# все категории переменной tariff_id с частотой 
# менее 55 наблюдений записываем в отдельную
# категорию 99
data.loc[data['tariff_id'].value_counts()[data['tariff_id']].values < 55, 
         'tariff_id'] = '99'

In [19]:
# выводим частоты категорий для переменной tariff_id
print(data['tariff_id'].value_counts(dropna=False))

2     69355
28    39117
19    15537
20    10970
25     7497
30     5538
22     3930
18     3339
3      3232
1      2245
23     2228
6      2102
29     1007
8       766
4       717
9       579
7       540
32      414
10      376
11      370
31      317
12      303
21      132
99       79
13       56
Name: tariff_id, dtype: int64

In [20]:
# выводим частоты для последних 10 категорий
# переменной living_region
print(data['living_region'].value_counts(dropna=False).tail(10))

РЕСПУБЛИКА КАЛМЫКИЯ             305
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ    203
NaN                             192
МАГАДАНСКАЯ ОБЛАСТЬ             159
РЕСПУБЛИКА ДАГЕСТАН              69
РЕСПУБЛИКА АЛТАЙ                 54
ЧУКОТСКИЙ АВТОНОМНЫЙ ОКРУГ       32
ЧЕЧЕНСКАЯ РЕСПУБЛИКА             31
РЕСПУБЛИКА ИНГУШЕТИЯ             19
ЧИТИНСКАЯ ОБЛАСТЬ                17
Name: living_region, dtype: int64

In [21]:
# все категории переменной living_region с частотой 
# <= 50 наблюдений записываем в отдельную
# категорию OTHER
data['living_region'].loc[data.groupby ('living_region')['living_region'].
                          transform ('count').fillna(data['living_region'].
                          isnull().sum()) <= 50] = 'OTHER'

In [22]:
# выводим частоты для последних 10 категорий 
# переменной living_region
print(data['living_region'].value_counts(dropna=False).tail(10))

РЕСПУБЛИКА ХАКАСИЯ                     480
КАМЧАТСКИЙ КРАЙ                        412
РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ    379
РЕСПУБЛИКА КАЛМЫКИЯ                    305
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ           203
NaN                                    192
МАГАДАНСКАЯ ОБЛАСТЬ                    159
OTHER                                   99
РЕСПУБЛИКА ДАГЕСТАН                     69
РЕСПУБЛИКА АЛТАЙ                        54
Name: living_region, dtype: int64

# Разбиение набора данных на обучающую и контрольную

In [23]:
# с помощью метода .sample из исходного 
# датафрейма data случайно отбираем 
# 70% наблюдений в обучающий датафрейм train
train=data.sample(frac=0.7,random_state=200)

# в исходном датафрейме data оставляем только те 
# наблюдения, индексные метки которых отличаются 
# от индекса наблюдений, попавших в обучающий датафрейм 
# train, и записываем контрольный датафрейм test
test=data.drop(train.index)

In [24]:
# выводим информацию о количестве пропусков
# по каждой переменной в обучающей выборке
train.isnull().sum()

gender                     0
age                        2
marital_status             1
job_position               0
credit_sum                 0
credit_month               0
tariff_id                  0
score_shk                  3
education                  2
living_region            139
monthly_income             1
credit_count            6477
overdue_credit_count    6477
open_account_flg           0
dtype: int64

In [25]:
# выводим информацию о количестве пропусков
# по каждой переменной в контрольной выборке
test.isnull().sum()

gender                     0
age                        0
marital_status             1
job_position               0
credit_sum                 1
credit_month               0
tariff_id                  0
score_shk                  0
education                  1
living_region             53
monthly_income             0
credit_count            2753
overdue_credit_count    2753
open_account_flg           0
dtype: int64

In [26]:
# заполняем пропуски в переменной age медианой
train['age'].fillna(train['age'].median(), inplace=True)
test['age'].fillna(train['age'].median(), inplace=True)

In [27]:
# заполняем пропуски в переменных credit_sum, score_shk 
# и monthly_income медианами
for i in ['credit_sum', 'score_shk', 'monthly_income']:
    if i in train.columns:
        train[i].fillna(train[i].median(), inplace=True)

for i in ['credit_sum', 'score_shk', 'monthly_income']:
    if i in test.columns:
        test[i].fillna(train[i].median(), inplace=True)

In [28]:
# заполняем пропуски в переменных credit_count,
# overdue_credit_count -1
for i in ['credit_count', 'overdue_credit_count']:
    if i in train.columns:
        train[i].fillna(-1, inplace=True)

for i in ['credit_count', 'overdue_credit_count']:
    if i in test.columns:
        test[i].fillna(-1, inplace=True)

In [29]:
# выводим частоты категорий
# для переменной marital_status
print(train['marital_status'].value_counts(dropna=False))
print(test['marital_status'].value_counts(dropna=False))

MAR    65652
UNM    36580
DIV    11919
CIV     2942
WID     2428
NaN        1
Name: marital_status, dtype: int64
MAR    28303
UNM    15568
DIV     5051
CIV     1254
WID     1047
NaN        1
Name: marital_status, dtype: int64

In [30]:
# выполняем импутацию пропусков модой
train['marital_status'] = train['marital_status'].fillna('MAR')
test['marital_status'] = test['marital_status'].fillna('MAR')

In [31]:
# выводим частоты категорий
# для переменной marital_status
print(train['marital_status'].value_counts(dropna=False))
print(test['marital_status'].value_counts(dropna=False))

MAR    65653
UNM    36580
DIV    11919
CIV     2942
WID     2428
Name: marital_status, dtype: int64
MAR    28304
UNM    15568
DIV     5051
CIV     1254
WID     1047
Name: marital_status, dtype: int64

In [32]:
# вычисляем моду для переменной
# education
train['education'].mode()

0    SCH
dtype: object

In [33]:
# выполняем импутацию пропусков модой
train['education'] = train['education'].fillna('SCH')
test['education'] = test['education'].fillna('SCH')

In [34]:
# выводим частоты для последних 10 категорий
# переменной living_region
print(train['living_region'].value_counts(dropna=False).tail(10))
print(test['living_region'].value_counts(dropna=False).tail(10))

КОСТРОМСКАЯ ОБЛАСТЬ                    343
КАМЧАТСКИЙ КРАЙ                        294
РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ    262
РЕСПУБЛИКА КАЛМЫКИЯ                    210
NaN                                    139
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ           132
МАГАДАНСКАЯ ОБЛАСТЬ                    115
OTHER                                   67
РЕСПУБЛИКА ДАГЕСТАН                     48
РЕСПУБЛИКА АЛТАЙ                        36
Name: living_region, dtype: int64
РЕСПУБЛИКА ХАКАСИЯ                     136
КАМЧАТСКИЙ КРАЙ                        118
РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ    117
РЕСПУБЛИКА КАЛМЫКИЯ                     95
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ            71
NaN                                     53
МАГАДАНСКАЯ ОБЛАСТЬ                     44
OTHER                                   32
РЕСПУБЛИКА ДАГЕСТАН                     21
РЕСПУБЛИКА АЛТАЙ                        18
Name: living_region, dtype: int64

In [35]:
# присваиваем переменной living_region тип str, 
# тем самым записывая пропуски в отдельную
# категорию nan
train['living_region']=train['living_region'].astype('str')
test['living_region']=test['living_region'].astype('str')

In [36]:
# выводим частоты для последних 10 категорий
# переменной living_region
print(train['living_region'].value_counts(dropna=False).tail(10))
print(test['living_region'].value_counts(dropna=False).tail(10))

КОСТРОМСКАЯ ОБЛАСТЬ                    343
КАМЧАТСКИЙ КРАЙ                        294
РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ    262
РЕСПУБЛИКА КАЛМЫКИЯ                    210
nan                                    139
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ           132
МАГАДАНСКАЯ ОБЛАСТЬ                    115
OTHER                                   67
РЕСПУБЛИКА ДАГЕСТАН                     48
РЕСПУБЛИКА АЛТАЙ                        36
Name: living_region, dtype: int64
РЕСПУБЛИКА ХАКАСИЯ                     136
КАМЧАТСКИЙ КРАЙ                        118
РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ    117
РЕСПУБЛИКА КАЛМЫКИЯ                     95
ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ            71
nan                                     53
МАГАДАНСКАЯ ОБЛАСТЬ                     44
OTHER                                   32
РЕСПУБЛИКА ДАГЕСТАН                     21
РЕСПУБЛИКА АЛТАЙ                        18
Name: living_region, dtype: int64

# Конструирование новых признаков

In [37]:
# на основе категориальной переменной tariff_id создаем
# количественную переменную tariff
train['tariff']=train['tariff_id'].astype('int')
test['tariff']=test['tariff_id'].astype('int')

In [38]:
# создаем переменную paym, которая 
# является отношением выданной суммы кредита 
# (credit_sum) к сроку кредита (credit_month), 
# то есть ежемесячной суммой кредита
train['paym'] = train['credit_sum'] / train['credit_month']
test['paym'] = test['credit_sum'] / test['credit_month']

# создаем переменную pti, которая является 
# отношением ежемесячной суммы кредита 
# (paym) к ежемесячному заработку 
# (monthly_income) 
train['pti'] = train['paym'] / train['monthly_income']
test['pti'] = test['paym'] / test['monthly_income']

# заменяем бесконечные значения на 1
train['pti'][train['pti'] == np.inf] = 1
test['pti'][test['pti'] == np.inf] = 1

In [39]:
# создаем новые переменные, возведя некоторые
# количественные переменные в квадрат
train['tariff_sq'] = train['tariff']**2
test['tariff_sq'] = test['tariff']**2

train['age_sq'] = train['age']**2
test['age_sq'] = test['age']**2

train['credit_sum_sq'] = train['credit_sum']**2
test['credit_sum_sq'] = test['credit_sum']**2

train['score_sq'] = train['score_shk']**2
test['score_sq'] = test['score_shk']**2

train['income_sq'] = train['monthly_income']**2
test['income_sq'] = test['monthly_income']**2

train['credit_month_sq'] = train['credit_month']**2
test['credit_month_sq'] = test['credit_month']**2

train['credit_count_sq'] = train['credit_count']**2
test['credit_count_sq'] = test['credit_count']**2

## Создание переменной, у которой значения основаны на значениях исходной переменной

In [40]:
# выводим уникальные значения исходной переменной, 
# в данном случае - значения переменной job_position
print(train['job_position'].unique())

['SPC' 'UMN' 'BIS' 'DIR' 'PNA' 'ATP' 'OTHER' 'WRK' 'BIU' 'NOR' 'WOI' 'INP'
 'PNI' 'WRP']

In [41]:
# затем создаем словарь, в котором ключом будет значение 
# исходной переменной job_position, а значением - значение 
# будущей переменной avrzarplata
dct = {'UMN': 51000, 'SPC': 63000, 'INP': 55000, 'DIR': 60000, 
       'ATP': 46000, 'PNA': 71000, 'BIS': 86000, 'WOI': 76000,
       'NOR': 54000,'WRK': 77000, 'WRP': 75000, 'PNV': 67000, 
       'BIU': 43000, 'PNI': 69000, 'HSK': 74000, 'PNS': 44000, 
       'INV': 88000, 'ONB': 62000, 'OTHER':20000}
# Создаем новую переменную avrzarplata, у которой значения 
# сопоставлены значениям переменной job_position
train['avrzarplata'] = train['job_position'].map(dct)
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,paym,pti,tariff_sq,age_sq,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata
53397,M,28.0,UNM,SPC,33579.0,10,20,0.431360,SCH,АМУРСКАЯ ОБЛАСТЬ,...,3357.900000,0.093275,400,784.0,1.127549e+09,0.186071,1.296000e+09,100,4.0,63000
143962,M,38.0,UNM,SPC,23511.0,10,19,0.358472,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,2351.100000,0.052247,361,1444.0,5.527671e+08,0.128502,2.025000e+09,100,4.0,63000
146922,F,25.0,MAR,SPC,39990.0,24,25,0.613475,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,1666.250000,0.033325,625,625.0,1.599200e+09,0.376352,2.500000e+09,576,36.0,63000
63697,F,65.0,UNM,UMN,3490.0,6,18,0.371355,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,581.666667,0.016619,324,4225.0,1.218010e+07,0.137905,1.225000e+09,36,16.0,51000
54503,M,49.0,MAR,BIS,36358.0,10,28,0.645187,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,3635.800000,0.072716,784,2401.0,1.321904e+09,0.416266,2.500000e+09,100,4.0,86000

In [42]:
# отключаем экспоненциальную запись
pd.set_option('display.float_format', lambda x: '%.3f' % x)
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,paym,pti,tariff_sq,age_sq,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,3357.900,0.093,400,784.000,1127549241.000,0.186,1296000000.000,100,4.000,63000
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,2351.100,0.052,361,1444.000,552767121.000,0.129,2025000000.000,100,4.000,63000
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,1666.250,0.033,625,625.000,1599200100.000,0.376,2500000000.000,576,36.000,63000
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,581.667,0.017,324,4225.000,12180100.000,0.138,1225000000.000,36,16.000,51000
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,3635.800,0.073,784,2401.000,1321904164.000,0.416,2500000000.000,100,4.000,86000

## Создание переменной, у которой каждое значение – частота наблюдений в категории переменных

In [43]:
# cоздаем переменную region_cnt, у которой каждое значение - 
# частота наблюдений в категории переменной living_region
train['region_cnt'] = train['living_region'].map(train['living_region'].value_counts())
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,pti,tariff_sq,age_sq,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata,region_cnt
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,0.093,400,784.000,1127549241.000,0.186,1296000000.000,100,4.000,63000,618
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,0.052,361,1444.000,552767121.000,0.129,2025000000.000,100,4.000,63000,3236
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,0.033,625,625.000,1599200100.000,0.376,2500000000.000,576,36.000,63000,3024
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,0.017,324,4225.000,12180100.000,0.138,1225000000.000,36,16.000,51000,344
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,0.073,784,2401.000,1321904164.000,0.416,2500000000.000,100,4.000,86000,3620

## Создание переменной, у которой каждое значение - среднее значение количественной переменной, взятое по уровню категориальной переменной

In [44]:
# пишем функцию, создающую переменную, у которой каждое 
# значение будет средним значением количественной
# переменной (real_feature), взятым по уровню 
# категориальной переменной (cat_feature)
def code_mean(df, cat_feature, real_feature):
    return (df[cat_feature].map(df.groupby(cat_feature)[real_feature].mean()))

# cоздаем переменную, у которой каждое значение - 
# среднее значение monthly_income в 
# категории переменной living_region
train['region_mean_income'] = code_mean(train, 'living_region', 'monthly_income')
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,tariff_sq,age_sq,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata,region_cnt,region_mean_income
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,400,784.000,1127549241.000,0.186,1296000000.000,100,4.000,63000,618,38026.071
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,361,1444.000,552767121.000,0.129,2025000000.000,100,4.000,63000,3236,32589.184
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,625,625.000,1599200100.000,0.376,2500000000.000,576,36.000,63000,3024,34645.748
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,324,4225.000,12180100.000,0.138,1225000000.000,36,16.000,51000,344,33443.198
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,784,2401.000,1321904164.000,0.416,2500000000.000,100,4.000,86000,3620,34010.613

## Создание категориальной переменной в результате конъюнкции двух переменных

In [45]:
# пишем функцию, которая создает переменную 
# в результате конъюнкции переменных 
# feature1 и feature2
def make_conj(df, feature1, feature2):
    df[feature1 + ' + ' + feature2] = df[feature1].astype(str) + ' + ' + df[feature2].astype(str)
    return (df)
make_conj(train, 'education', 'marital_status')

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,age_sq,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata,region_cnt,region_mean_income,education + marital_status
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,784.000,1127549241.000,0.186,1296000000.000,100,4.000,63000,618,38026.071,SCH + UNM
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,1444.000,552767121.000,0.129,2025000000.000,100,4.000,63000,3236,32589.184,GRD + UNM
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,625.000,1599200100.000,0.376,2500000000.000,576,36.000,63000,3024,34645.748,GRD + MAR
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,4225.000,12180100.000,0.138,1225000000.000,36,16.000,51000,344,33443.198,GRD + UNM
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,2401.000,1321904164.000,0.416,2500000000.000,100,4.000,86000,3620,34010.613,SCH + MAR
115316,F,39.000,UNM,SPC,13209.000,10,2,0.455,SCH,РЕСПУБЛИКА САХА (ЯКУТИЯ),...,1521.000,174477681.000,0.207,3600000000.000,100,1.000,63000,1281,55261.237,SCH + UNM
16354,M,30.000,UNM,SPC,15192.050,12,2,0.452,SCH,РЕСПУБЛИКА ТАТАРСТАН,...,900.000,230798383.202,0.204,625000000.000,144,1.000,63000,5368,36299.226,SCH + UNM
98227,F,44.000,WID,SPC,27894.000,10,19,0.493,SCH,РЕСПУБЛИКА КАРЕЛИЯ,...,1936.000,778075236.000,0.243,1814760000.000,100,0.000,63000,466,41057.567,SCH + WID
69607,F,33.000,MAR,SPC,16116.470,10,2,0.479,SCH,КЕМЕРОВСКАЯ ОБЛАСТЬ,...,1089.000,259740605.261,0.230,400000000.000,100,16.000,63000,2066,31852.985,SCH + MAR
99745,F,30.000,UNM,SPC,3712.770,6,29,0.368,SCH,НИЖЕГОРОДСКАЯ ОБЛАСТЬ,...,900.000,13784661.073,0.135,400000000.000,36,9.000,63000,2602,33974.939,SCH + UNM
9710,F,52.000,UNM,SPC,58789.000,12,28,0.629,SCH,ВОЛГОГРАДСКАЯ ОБЛАСТЬ,...,2704.000,3456146521.000,0.396,1089000000.000,144,0.000,63000,1596,31503.996,SCH + UNM
127187,F,28.000,UNM,SPC,53188.000,10,28,0.701,GRD,ПРИМОРСКИЙ КРАЙ,...,784.000,2828963344.000,0.491,2704000000.000,100,1.000,63000,912,42266.414,GRD + UNM
145418,F,39.000,MAR,SPC,32567.000,13,2,0.471,SCH,КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА,...,1521.000,1060609489.000,0.222,1089000000.000,169,9.000,63000,460,33862.783,SCH + MAR
105210,F,45.000,UNM,UMN,36507.000,10,19,0.309,GRD,КРАСНОЯРСКИЙ КРАЙ,...,2025.000,1332761049.000,0.096,1225000000.000,100,0.000,51000,2181,41801.976,GRD + UNM
44006,M,24.000,UNM,SPC,16069.000,10,28,0.561,UGR,РЕСПУБЛИКА БАШКОРТОСТАН,...,576.000,258212761.000,0.315,576000000.000,100,0.000,63000,4527,34429.306,UGR + UNM
93178,M,44.000,MAR,UMN,46568.000,12,2,0.487,SCH,ЧУВАШСКАЯ РЕСПУБЛИКА,...,1936.000,2168578624.000,0.237,1600000000.000,144,1.000,51000,640,28391.628,SCH + MAR
66790,F,31.000,UNM,SPC,11190.000,14,2,0.381,SCH,ТВЕРСКАЯ ОБЛАСТЬ,...,961.000,125216100.000,0.145,729000000.000,196,16.000,63000,1071,33812.550,SCH + UNM
132148,F,55.000,DIV,SPC,7578.000,12,25,0.517,SCH,РЯЗАНСКАЯ ОБЛАСТЬ,...,3025.000,57426084.000,0.267,529000000.000,144,4.000,63000,499,33555.463,SCH + DIV
52656,F,43.000,CIV,SPC,30248.000,13,2,0.326,SCH,РЕСПУБЛИКА БАШКОРТОСТАН,...,1849.000,914941504.000,0.106,625000000.000,169,4.000,63000,4527,34429.306,SCH + CIV
124358,M,41.000,MAR,SPC,10019.000,12,2,0.375,SCH,МОСКВА,...,1681.000,100380361.000,0.141,1225000000.000,144,9.000,63000,6479,62409.768,SCH + MAR
139466,M,35.000,MAR,SPC,48369.000,12,2,0.474,GRD,МОСКОВСКАЯ ОБЛАСТЬ,...,1225.000,2339560161.000,0.224,8100000000.000,144,0.000,63000,8864,53279.124,GRD + MAR
74846,F,33.000,UNM,SPC,44287.000,12,18,0.574,GRD,МОСКВА,...,1089.000,1961338369.000,0.329,6400000000.000,144,9.000,63000,6479,62409.768,GRD + UNM
146802,F,29.000,UNM,DIR,42878.000,10,2,0.474,GRD,ИРКУТСКАЯ ОБЛАСТЬ,...,841.000,1838522884.000,0.224,4225000000.000,100,1.000,60000,3022,37558.886,GRD + UNM
41451,M,37.000,MAR,SPC,17353.330,10,2,0.488,SCH,ВОЛГОГРАДСКАЯ ОБЛАСТЬ,...,1369.000,301138062.089,0.238,900000000.000,100,0.000,63000,1596,31503.996,SCH + MAR
94502,F,47.000,WID,SPC,58789.000,18,2,0.464,SCH,МОСКВА,...,2209.000,3456146521.000,0.215,4096000000.000,324,1.000,63000,6479,62409.768,SCH + WID
13091,F,56.000,MAR,SPC,48834.000,10,10,0.444,GRD,САМАРСКАЯ ОБЛАСТЬ,...,3136.000,2384759556.000,0.198,484000000.000,100,16.000,63000,3551,34925.862,GRD + MAR
40220,F,39.000,MAR,SPC,22889.000,12,2,0.409,SCH,АМУРСКАЯ ОБЛАСТЬ,...,1521.000,523906321.000,0.168,625000000.000,144,16.000,63000,618,38026.071,SCH + MAR
98279,M,29.000,MAR,UMN,17704.550,12,2,0.381,GRD,ОМСКАЯ ОБЛАСТЬ,...,841.000,313451090.702,0.145,1225000000.000,144,1.000,51000,660,31604.333,GRD + MAR
51512,F,28.000,UNM,SPC,4990.000,12,2,0.435,GRD,РЕСПУБЛИКА БАШКОРТОСТАН,...,784.000,24900100.000,0.189,225000000.000,144,1.000,63000,4527,34429.306,GRD + UNM
169234,M,48.000,DIV,PNA,29278.000,14,2,0.564,SCH,ВОРОНЕЖСКАЯ ОБЛАСТЬ,...,2304.000,857201284.000,0.318,400000000.000,196,9.000,71000,1175,33642.059,SCH + DIV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68237,F,27.000,MAR,UMN,15279.000,10,20,0.417,GRD,ЧУВАШСКАЯ РЕСПУБЛИКА,...,729.000,233447841.000,0.174,1225000000.000,100,4.000,51000,640,28391.628,GRD + MAR
76297,M,44.000,MAR,SPC,74322.000,10,6,0.428,GRD,САНКТ-ПЕТЕРБУРГ,...,1936.000,5523759684.000,0.183,8100000000.000,100,4.000,63000,5840,50687.023,GRD + MAR
66924,F,26.000,UNM,SPC,14318.000,12,28,0.621,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,676.000,205005124.000,0.386,729000000.000,144,25.000,63000,3024,34645.748,GRD + UNM
97023,F,54.000,DIV,SPC,21068.000,10,2,0.310,SCH,НИЖЕГОРОДСКАЯ ОБЛАСТЬ,...,2916.000,443860624.000,0.096,225000000.000,100,1.000,63000,2602,33974.939,SCH + DIV
148262,F,36.000,MAR,SPC,13958.000,12,28,0.749,SCH,ПЕРМСКИЙ КРАЙ,...,1296.000,194825764.000,0.561,289000000.000,144,0.000,63000,2499,36624.497,SCH + MAR
50236,F,29.000,MAR,SPC,19692.050,12,28,0.582,SCH,РЕСПУБЛИКА КОМИ,...,841.000,387776833.202,0.339,121000000.000,144,1.000,63000,1290,44673.019,SCH + MAR
20410,M,25.000,UNM,SPC,13039.000,13,2,0.378,GRD,ИРКУТСКАЯ ОБЛАСТЬ,...,625.000,170015521.000,0.143,2500000000.000,169,1.000,63000,3022,37558.886,GRD + UNM
121966,M,26.000,MAR,SPC,22289.000,10,28,0.624,SCH,ПЕРМСКИЙ КРАЙ,...,676.000,496799521.000,0.389,625000000.000,100,4.000,63000,2499,36624.497,SCH + MAR
105221,F,59.000,UNM,SPC,12160.000,10,2,0.401,GRD,СВЕРДЛОВСКАЯ ОБЛАСТЬ,...,3481.000,147865600.000,0.161,1225000000.000,100,0.000,63000,5104,38225.178,GRD + UNM
127949,M,26.000,MAR,SPC,49980.000,24,2,0.430,SCH,МОСКВА,...,676.000,2498000400.000,0.185,4225000000.000,576,0.000,63000,6479,62409.768,SCH + MAR
127371,M,25.000,UNM,SPC,41174.000,10,3,0.427,GRD,РЕСПУБЛИКА БАШКОРТОСТАН,...,625.000,1695298276.000,0.182,2500000000.000,100,1.000,63000,4527,34429.306,GRD + UNM
110820,F,53.000,MAR,SPC,10860.000,10,28,0.635,SCH,КАЛУЖСКАЯ ОБЛАСТЬ,...,2809.000,117939600.000,0.404,900000000.000,100,16.000,63000,798,39051.223,SCH + MAR
157560,M,33.000,MAR,BIS,20223.000,10,3,0.316,GRD,РЕСПУБЛИКА БАШКОРТОСТАН,...,1089.000,408969729.000,0.100,6400000000.000,100,1.000,86000,4527,34429.306,GRD + MAR
127214,F,29.000,MAR,SPC,15990.000,12,2,0.433,GRD,РЕСПУБЛИКА ТАТАРСТАН,...,841.000,255680100.000,0.188,457960000.000,144,16.000,63000,5368,36299.226,GRD + MAR
122482,F,32.000,MAR,SPC,28058.000,12,2,0.447,GRD,КРАСНОДАРСКИЙ КРАЙ,...,1024.000,787251364.000,0.200,1225000000.000,144,16.000,63000,5859,37483.006,GRD + MAR
83945,M,55.000,MAR,UMN,49472.000,10,31,0.334,GRD,МОСКОВСКАЯ ОБЛАСТЬ,...,3025.000,2447478784.000,0.111,6400000000.000,100,16.000,51000,8864,53279.124,GRD + MAR
81614,M,42.000,MAR,SPC,27887.000,12,2,0.430,GRD,САНКТ-ПЕТЕРБУРГ,...,1764.000,777684769.000,0.185,13689000000.000,144,16.000,63000,5840,50687.023,GRD + MAR
24234,F,26.000,UNM,SPC,20468.000,10,2,0.294,GRD,МУРМАНСКАЯ ОБЛАСТЬ,...,676.000,418939024.000,0.087,1225000000.000,100,4.000,63000,1002,49557.378,GRD + UNM
121962,M,29.000,UNM,UMN,13818.000,10,2,0.386,GRD,МОСКВА,...,841.000,190937124.000,0.149,5625000000.000,100,4.000,51000,6479,62409.768,GRD + UNM
15063,M,25.000,UNM,SPC,22668.000,12,2,0.403,SCH,КРАСНОДАРСКИЙ КРАЙ,...,625.000,513838224.000,0.162,1225000000.000,144,4.000,63000,5859,37483.006,SCH + UNM
122853,M,43.000,MAR,SPC,15959.000,12,9,0.482,SCH,МОСКОВСКАЯ ОБЛАСТЬ,...,1849.000,254689681.000,0.232,6400000000.000,144,9.000,63000,8864,53279.124,SCH + MAR
64074,M,24.000,UNM,SPC,16389.000,10,28,0.554,GRD,КРАСНОДАРСКИЙ КРАЙ,...,576.000,268599321.000,0.307,3600000000.000,100,0.000,63000,5859,37483.006,GRD + UNM
150512,M,44.000,MAR,DIR,13889.000,12,2,0.366,SCH,АЛТАЙСКИЙ КРАЙ,...,1936.000,192904321.000,0.134,2500000000.000,144,16.000,60000,380,28905.887,SCH + MAR
156036,F,39.000,MAR,SPC,20406.000,10,19,0.516,SCH,СМОЛЕНСКАЯ ОБЛАСТЬ,...,1521.000,416404836.000,0.266,1225000000.000,100,1.000,63000,688,29088.449,SCH + MAR
162237,M,34.000,DIV,SPC,16608.000,10,2,0.440,SCH,СВЕРДЛОВСКАЯ ОБЛАСТЬ,...,1156.000,275825664.000,0.194,900000000.000,100,1.000,63000,5104,38225.178,SCH + DIV
24478,F,24.000,UNM,SPC,23664.000,4,25,0.187,GRD,ЯРОСЛАВСКАЯ ОБЛАСТЬ,...,576.000,559984896.000,0.035,676000000.000,16,1.000,63000,648,34266.588,GRD + UNM
12084,M,22.000,UNM,SPC,15248.000,12,22,0.676,SCH,ПЕНЗЕНСКАЯ ОБЛАСТЬ,...,484.000,232501504.000,0.457,1225000000.000,144,1.000,63000,649,31304.746,SCH + UNM
78434,F,27.000,MAR,SPC,60458.000,18,2,0.497,SCH,ЛЕНИНГРАДСКАЯ ОБЛАСТЬ,...,729.000,3655169764.000,0.247,2450250000.000,324,9.000,63000,2446,41985.454,SCH + MAR
69901,M,29.000,MAR,UMN,70589.000,8,28,0.598,GRD,МОСКВА,...,841.000,4982806921.000,0.358,32400000000.000,64,9.000,51000,6479,62409.768,GRD + MAR
149270,M,30.000,UNM,SPC,40321.110,10,28,0.768,SCH,МОСКОВСКАЯ ОБЛАСТЬ,...,900.000,1625791911.632,0.589,1600000000.000,100,4.000,63000,8864,53279.124,SCH + UNM

## Создание количественной переменной, у которой каждое значение - усредненное значение нескольких количественных переменных

In [46]:
# создаем переменную mean_age_tenure, у которой 
# каждое значение - усредненное значение 
# переменных age и credit_month 
train['mean_age_tenure'] = train[['age', 'credit_month']].mean(axis=1)
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata,region_cnt,region_mean_income,education + marital_status,mean_age_tenure
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,1127549241.000,0.186,1296000000.000,100,4.000,63000,618,38026.071,SCH + UNM,19.000
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,552767121.000,0.129,2025000000.000,100,4.000,63000,3236,32589.184,GRD + UNM,24.000
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,1599200100.000,0.376,2500000000.000,576,36.000,63000,3024,34645.748,GRD + MAR,24.500
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,12180100.000,0.138,1225000000.000,36,16.000,51000,344,33443.198,GRD + UNM,35.500
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,1321904164.000,0.416,2500000000.000,100,4.000,86000,3620,34010.613,SCH + MAR,29.500

## Категоризация (биннинг) количественной переменной

### Категоризация на основе интервалов, заданных вручную

In [47]:
# задаем точки, в которых будут находится границы категорий 
# (до 50000, от 50000 до 200000, от 200000 и выше) 
bins = [-np.inf, 50000, 200000, np.inf]
# задаем метки для категорий будущей переменной
group_names = ['Low', 'Average', 'High']
# осуществляем биннинг переменной monthly_income 
# и записываем результаты в новую переменную incomecat
train['incomecat'] = pd.cut(train['monthly_income'], bins, labels=group_names)
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,score_sq,income_sq,credit_month_sq,credit_count_sq,avrzarplata,region_cnt,region_mean_income,education + marital_status,mean_age_tenure,incomecat
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,0.186,1296000000.000,100,4.000,63000,618,38026.071,SCH + UNM,19.000,Low
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,0.129,2025000000.000,100,4.000,63000,3236,32589.184,GRD + UNM,24.000,Low
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,0.376,2500000000.000,576,36.000,63000,3024,34645.748,GRD + MAR,24.500,Low
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,0.138,1225000000.000,36,16.000,51000,344,33443.198,GRD + UNM,35.500,Low
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,0.416,2500000000.000,100,4.000,86000,3620,34010.613,SCH + MAR,29.500,Low

### Категоризация на основе децилей

In [48]:
# осуществляем биннинг переменной monthly_income 
# на основе децилей и записываем результаты 
# в новую переменную income_decile
train['income_decile'] = pd.qcut(train['monthly_income'], 10)
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,income_sq,credit_month_sq,credit_count_sq,avrzarplata,region_cnt,region_mean_income,education + marital_status,mean_age_tenure,incomecat,income_decile
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,1296000000.000,100,4.000,63000,618,38026.071,SCH + UNM,19.000,Low,"(35000.0, 40000.0]"
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,2025000000.000,100,4.000,63000,3236,32589.184,GRD + UNM,24.000,Low,"(40000.0, 45000.0]"
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,2500000000.000,576,36.000,63000,3024,34645.748,GRD + MAR,24.500,Low,"(45000.0, 50000.0]"
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,1225000000.000,36,16.000,51000,344,33443.198,GRD + UNM,35.500,Low,"(30000.0, 35000.0]"
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,2500000000.000,100,4.000,86000,3620,34010.613,SCH + MAR,29.500,Low,"(45000.0, 50000.0]"

## Создание бинарной переменной на основе значений количественной переменной

In [49]:
# создаем новую переменную retired, которая принимает 
# значение "Yes", если значение переменной age больше 60, 
# и значение "No" в противном случае
train['retired'] = np.where(train['age']>=60, 'Yes', 'No')
train.head()

,gender,age,marital_status,job_position,credit_sum,credit_month,tariff_id,score_shk,education,living_region,...,credit_month_sq,credit_count_sq,avrzarplata,region_cnt,region_mean_income,education + marital_status,mean_age_tenure,incomecat,income_decile,retired
53397,M,28.000,UNM,SPC,33579.000,10,20,0.431,SCH,АМУРСКАЯ ОБЛАСТЬ,...,100,4.000,63000,618,38026.071,SCH + UNM,19.000,Low,"(35000.0, 40000.0]",No
143962,M,38.000,UNM,SPC,23511.000,10,19,0.358,GRD,СТАВРОПОЛЬСКИЙ КРАЙ,...,100,4.000,63000,3236,32589.184,GRD + UNM,24.000,Low,"(40000.0, 45000.0]",No
146922,F,25.000,MAR,SPC,39990.000,24,25,0.613,GRD,РОСТОВСКАЯ ОБЛАСТЬ,...,576,36.000,63000,3024,34645.748,GRD + MAR,24.500,Low,"(45000.0, 50000.0]",No
63697,F,65.000,UNM,UMN,3490.000,6,18,0.371,GRD,РЕСПУБЛИКА ХАКАСИЯ,...,36,16.000,51000,344,33443.198,GRD + UNM,35.500,Low,"(30000.0, 35000.0]",Yes
54503,M,49.000,MAR,BIS,36358.000,10,28,0.645,SCH,ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,...,100,4.000,86000,3620,34010.613,SCH + MAR,29.500,Low,"(45000.0, 50000.0]",No

In [50]:
# удаляем переменные, созданные в ходе наших "экспериментов"
train.drop(['avrzarplata', 'region_cnt', 'region_mean_income', 
            'education + marital_status', 'mean_age_tenure', 'incomecat', 
            'income_decile', 'retired'], axis=1, inplace=True)

In [51]:
# убеждаемся в отсутствии пропусков в переменных, а также 
# в одинаковом количестве переменных в обучающей 
# и контрольной выборках
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119522 entries, 53397 to 149270
Data columns (total 24 columns):
gender                  119522 non-null object
age                     119522 non-null float64
marital_status          119522 non-null object
job_position            119522 non-null object
credit_sum              119522 non-null float64
credit_month            119522 non-null int64
tariff_id               119522 non-null object
score_shk               119522 non-null float64
education               119522 non-null object
living_region           119522 non-null object
monthly_income          119522 non-null float64
credit_count            119522 non-null float64
overdue_credit_count    119522 non-null float64
open_account_flg        119522 non-null object
tariff                  119522 non-null int32
paym                    119522 non-null float64
pti                     119522 non-null float64
tariff_sq               119522 non-null int32
age_sq                  119522 non-null float64
credit_sum_sq           119522 non-null float64
score_sq                119522 non-null float64
income_sq               119522 non-null float64
credit_month_sq         119522 non-null int64
credit_count_sq         119522 non-null float64
dtypes: float64(13), int32(2), int64(2), object(7)
memory usage: 21.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 51224 entries, 0 to 170745
Data columns (total 24 columns):
gender                  51224 non-null object
age                     51224 non-null float64
marital_status          51224 non-null object
job_position            51224 non-null object
credit_sum              51224 non-null float64
credit_month            51224 non-null int64
tariff_id               51224 non-null object
score_shk               51224 non-null float64
education               51224 non-null object
living_region           51224 non-null object
monthly_income          51224 non-null float64
credit_count            51224 non-null float64
overdue_credit_count    51224 non-null float64
open_account_flg        51224 non-null object
tariff                  51224 non-null int32
paym                    51224 non-null float64
pti                     51224 non-null float64
tariff_sq               51224 non-null int32
age_sq                  51224 non-null float64
credit_sum_sq           51224 non-null float64
score_sq                51224 non-null float64
income_sq               51224 non-null float64
credit_month_sq         51224 non-null int64
credit_count_sq         51224 non-null float64
dtypes: float64(13), int32(2), int64(2), object(7)
memory usage: 9.4+ MB
None

In [52]:
# печатаем названия столбцов до и после
# дамми-кодирования
print("Исходные переменные:\n", list(train.columns), "\n")
train_dummies = pd.get_dummies(train)
print("Переменные после get_dummies:\n", list(train_dummies.columns))

print("Исходные переменные:\n", list(test.columns), "\n")
test_dummies = pd.get_dummies(test)
print("Переменные после get_dummies:\n", list(test_dummies.columns))

Исходные переменные:
 ['gender', 'age', 'marital_status', 'job_position', 'credit_sum', 'credit_month', 'tariff_id', 'score_shk', 'education', 'living_region', 'monthly_income', 'credit_count', 'overdue_credit_count', 'open_account_flg', 'tariff', 'paym', 'pti', 'tariff_sq', 'age_sq', 'credit_sum_sq', 'score_sq', 'income_sq', 'credit_month_sq', 'credit_count_sq']

Переменные после get_dummies:
 ['age', 'credit_sum', 'credit_month', 'score_shk', 'monthly_income', 'credit_count', 'overdue_credit_count', 'tariff', 'paym', 'pti', 'tariff_sq', 'age_sq', 'credit_sum_sq', 'score_sq', 'income_sq', 'credit_month_sq', 'credit_count_sq', 'gender_F', 'gender_M', 'marital_status_CIV', 'marital_status_DIV', 'marital_status_MAR', 'marital_status_UNM', 'marital_status_WID', 'job_position_ATP', 'job_position_BIS', 'job_position_BIU', 'job_position_DIR', 'job_position_INP', 'job_position_NOR', 'job_position_OTHER', 'job_position_PNA', 'job_position_PNI', 'job_position_SPC', 'job_position_UMN', 'job_position_WOI', 'job_position_WRK', 'job_position_WRP', 'tariff_id_1', 'tariff_id_2', 'tariff_id_3', 'tariff_id_4', 'tariff_id_6', 'tariff_id_7', 'tariff_id_8', 'tariff_id_9', 'tariff_id_10', 'tariff_id_11', 'tariff_id_12', 'tariff_id_13', 'tariff_id_18', 'tariff_id_19', 'tariff_id_20', 'tariff_id_21', 'tariff_id_22', 'tariff_id_23', 'tariff_id_25', 'tariff_id_28', 'tariff_id_29', 'tariff_id_30', 'tariff_id_31', 'tariff_id_32', 'tariff_id_99', 'education_ACD', 'education_GRD', 'education_PGR', 'education_SCH', 'education_UGR', 'living_region_OTHER', 'living_region_nan', 'living_region_АЛТАЙСКИЙ КРАЙ', 'living_region_АМУРСКАЯ ОБЛАСТЬ', 'living_region_АРХАНГЕЛЬСКАЯ ОБЛАСТЬ', 'living_region_АСТРАХАНСКАЯ ОБЛАСТЬ', 'living_region_БЕЛГОРОДСКАЯ ОБЛАСТЬ', 'living_region_БРЯНСКАЯ ОБЛАСТЬ', 'living_region_ВЛАДИМИРСКАЯ ОБЛАСТЬ', 'living_region_ВОЛГОГРАДСКАЯ ОБЛАСТЬ', 'living_region_ВОЛОГОДСКАЯ ОБЛАСТЬ', 'living_region_ВОРОНЕЖСКАЯ ОБЛАСТЬ', 'living_region_ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ', 'living_region_ЗАБАЙКАЛЬСКИЙ КРАЙ', 'living_region_ИВАНОВСКАЯ ОБЛАСТЬ', 'living_region_ИРКУТСКАЯ ОБЛАСТЬ', 'living_region_КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА', 'living_region_КАЛИНИНГРАДСКАЯ ОБЛАСТЬ', 'living_region_КАЛУЖСКАЯ ОБЛАСТЬ', 'living_region_КАМЧАТСКИЙ КРАЙ', 'living_region_КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСПУБЛИКА', 'living_region_КЕМЕРОВСКАЯ ОБЛАСТЬ', 'living_region_КИРОВСКАЯ ОБЛАСТЬ', 'living_region_КОСТРОМСКАЯ ОБЛАСТЬ', 'living_region_КРАСНОДАРСКИЙ КРАЙ', 'living_region_КРАСНОЯРСКИЙ КРАЙ', 'living_region_КУРГАНСКАЯ ОБЛАСТЬ', 'living_region_КУРСКАЯ ОБЛАСТЬ', 'living_region_ЛЕНИНГРАДСКАЯ ОБЛАСТЬ', 'living_region_ЛИПЕЦКАЯ ОБЛАСТЬ', 'living_region_МАГАДАНСКАЯ ОБЛАСТЬ', 'living_region_МОСКВА', 'living_region_МОСКОВСКАЯ ОБЛАСТЬ', 'living_region_МУРМАНСКАЯ ОБЛАСТЬ', 'living_region_НИЖЕГОРОДСКАЯ ОБЛАСТЬ', 'living_region_НОВГОРОДСКАЯ ОБЛАСТЬ', 'living_region_НОВОСИБИРСКАЯ ОБЛАСТЬ', 'living_region_ОМСКАЯ ОБЛАСТЬ', 'living_region_ОРЕНБУРГСКАЯ ОБЛАСТЬ', 'living_region_ОРЛОВСКАЯ ОБЛАСТЬ', 'living_region_ПЕНЗЕНСКАЯ ОБЛАСТЬ', 'living_region_ПЕРМСКИЙ КРАЙ', 'living_region_ПРИМОРСКИЙ КРАЙ', 'living_region_ПСКОВСКАЯ ОБЛАСТЬ', 'living_region_РЕСПУБЛИКА АДЫГЕЯ', 'living_region_РЕСПУБЛИКА АЛТАЙ', 'living_region_РЕСПУБЛИКА БАШКОРТОСТАН', 'living_region_РЕСПУБЛИКА БУРЯТИЯ', 'living_region_РЕСПУБЛИКА ДАГЕСТАН', 'living_region_РЕСПУБЛИКА КАЛМЫКИЯ', 'living_region_РЕСПУБЛИКА КАРЕЛИЯ', 'living_region_РЕСПУБЛИКА КОМИ', 'living_region_РЕСПУБЛИКА МАРИЙ ЭЛ', 'living_region_РЕСПУБЛИКА МОРДОВИЯ', 'living_region_РЕСПУБЛИКА САХА (ЯКУТИЯ)', 'living_region_РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ', 'living_region_РЕСПУБЛИКА ТАТАРСТАН', 'living_region_РЕСПУБЛИКА ТЫВА', 'living_region_РЕСПУБЛИКА ХАКАСИЯ', 'living_region_РОСТОВСКАЯ ОБЛАСТЬ', 'living_region_РЯЗАНСКАЯ ОБЛАСТЬ', 'living_region_САМАРСКАЯ ОБЛАСТЬ', 'living_region_САНКТ-ПЕТЕРБУРГ', 'living_region_САРАТОВСКАЯ ОБЛАСТЬ', 'living_region_САХАЛИНСКАЯ ОБЛАСТЬ', 'living_region_СВЕРДЛОВСКАЯ ОБЛАСТЬ', 'living_region_СМОЛЕНСКАЯ ОБЛАСТЬ', 'living_region_СТАВРОПОЛЬСКИЙ КРАЙ', 'living_region_ТАМБОВСКАЯ ОБЛАСТЬ', 'living_region_ТВЕРСКАЯ ОБЛАСТЬ', 'living_region_ТОМСКАЯ ОБЛАСТЬ', 'living_region_ТУЛЬСКАЯ ОБЛАСТЬ', 'living_region_ТЮМЕНСКАЯ ОБЛАСТЬ', 'living_region_УДМУРТСКАЯ РЕСПУБЛИКА', 'living_region_УЛЬЯНОВСКАЯ ОБЛАСТЬ', 'living_region_ХАБАРОВСКИЙ КРАЙ', 'living_region_ЧЕЛЯБИНСКАЯ ОБЛАСТЬ', 'living_region_ЧУВАШСКАЯ РЕСПУБЛИКА', 'living_region_ЯРОСЛАВСКАЯ ОБЛАСТЬ', 'open_account_flg_0', 'open_account_flg_1']
Исходные переменные:
 ['gender', 'age', 'marital_status', 'job_position', 'credit_sum', 'credit_month', 'tariff_id', 'score_shk', 'education', 'living_region', 'monthly_income', 'credit_count', 'overdue_credit_count', 'open_account_flg', 'tariff', 'paym', 'pti', 'tariff_sq', 'age_sq', 'credit_sum_sq', 'score_sq', 'income_sq', 'credit_month_sq', 'credit_count_sq']

Переменные после get_dummies:
 ['age', 'credit_sum', 'credit_month', 'score_shk', 'monthly_income', 'credit_count', 'overdue_credit_count', 'tariff', 'paym', 'pti', 'tariff_sq', 'age_sq', 'credit_sum_sq', 'score_sq', 'income_sq', 'credit_month_sq', 'credit_count_sq', 'gender_F', 'gender_M', 'marital_status_CIV', 'marital_status_DIV', 'marital_status_MAR', 'marital_status_UNM', 'marital_status_WID', 'job_position_ATP', 'job_position_BIS', 'job_position_BIU', 'job_position_DIR', 'job_position_INP', 'job_position_NOR', 'job_position_OTHER', 'job_position_PNA', 'job_position_PNI', 'job_position_SPC', 'job_position_UMN', 'job_position_WOI', 'job_position_WRK', 'job_position_WRP', 'tariff_id_1', 'tariff_id_2', 'tariff_id_3', 'tariff_id_4', 'tariff_id_6', 'tariff_id_7', 'tariff_id_8', 'tariff_id_9', 'tariff_id_10', 'tariff_id_11', 'tariff_id_12', 'tariff_id_13', 'tariff_id_18', 'tariff_id_19', 'tariff_id_20', 'tariff_id_21', 'tariff_id_22', 'tariff_id_23', 'tariff_id_25', 'tariff_id_28', 'tariff_id_29', 'tariff_id_30', 'tariff_id_31', 'tariff_id_32', 'tariff_id_99', 'education_ACD', 'education_GRD', 'education_PGR', 'education_SCH', 'education_UGR', 'living_region_OTHER', 'living_region_nan', 'living_region_АЛТАЙСКИЙ КРАЙ', 'living_region_АМУРСКАЯ ОБЛАСТЬ', 'living_region_АРХАНГЕЛЬСКАЯ ОБЛАСТЬ', 'living_region_АСТРАХАНСКАЯ ОБЛАСТЬ', 'living_region_БЕЛГОРОДСКАЯ ОБЛАСТЬ', 'living_region_БРЯНСКАЯ ОБЛАСТЬ', 'living_region_ВЛАДИМИРСКАЯ ОБЛАСТЬ', 'living_region_ВОЛГОГРАДСКАЯ ОБЛАСТЬ', 'living_region_ВОЛОГОДСКАЯ ОБЛАСТЬ', 'living_region_ВОРОНЕЖСКАЯ ОБЛАСТЬ', 'living_region_ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ', 'living_region_ЗАБАЙКАЛЬСКИЙ КРАЙ', 'living_region_ИВАНОВСКАЯ ОБЛАСТЬ', 'living_region_ИРКУТСКАЯ ОБЛАСТЬ', 'living_region_КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА', 'living_region_КАЛИНИНГРАДСКАЯ ОБЛАСТЬ', 'living_region_КАЛУЖСКАЯ ОБЛАСТЬ', 'living_region_КАМЧАТСКИЙ КРАЙ', 'living_region_КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСПУБЛИКА', 'living_region_КЕМЕРОВСКАЯ ОБЛАСТЬ', 'living_region_КИРОВСКАЯ ОБЛАСТЬ', 'living_region_КОСТРОМСКАЯ ОБЛАСТЬ', 'living_region_КРАСНОДАРСКИЙ КРАЙ', 'living_region_КРАСНОЯРСКИЙ КРАЙ', 'living_region_КУРГАНСКАЯ ОБЛАСТЬ', 'living_region_КУРСКАЯ ОБЛАСТЬ', 'living_region_ЛЕНИНГРАДСКАЯ ОБЛАСТЬ', 'living_region_ЛИПЕЦКАЯ ОБЛАСТЬ', 'living_region_МАГАДАНСКАЯ ОБЛАСТЬ', 'living_region_МОСКВА', 'living_region_МОСКОВСКАЯ ОБЛАСТЬ', 'living_region_МУРМАНСКАЯ ОБЛАСТЬ', 'living_region_НИЖЕГОРОДСКАЯ ОБЛАСТЬ', 'living_region_НОВГОРОДСКАЯ ОБЛАСТЬ', 'living_region_НОВОСИБИРСКАЯ ОБЛАСТЬ', 'living_region_ОМСКАЯ ОБЛАСТЬ', 'living_region_ОРЕНБУРГСКАЯ ОБЛАСТЬ', 'living_region_ОРЛОВСКАЯ ОБЛАСТЬ', 'living_region_ПЕНЗЕНСКАЯ ОБЛАСТЬ', 'living_region_ПЕРМСКИЙ КРАЙ', 'living_region_ПРИМОРСКИЙ КРАЙ', 'living_region_ПСКОВСКАЯ ОБЛАСТЬ', 'living_region_РЕСПУБЛИКА АДЫГЕЯ', 'living_region_РЕСПУБЛИКА АЛТАЙ', 'living_region_РЕСПУБЛИКА БАШКОРТОСТАН', 'living_region_РЕСПУБЛИКА БУРЯТИЯ', 'living_region_РЕСПУБЛИКА ДАГЕСТАН', 'living_region_РЕСПУБЛИКА КАЛМЫКИЯ', 'living_region_РЕСПУБЛИКА КАРЕЛИЯ', 'living_region_РЕСПУБЛИКА КОМИ', 'living_region_РЕСПУБЛИКА МАРИЙ ЭЛ', 'living_region_РЕСПУБЛИКА МОРДОВИЯ', 'living_region_РЕСПУБЛИКА САХА (ЯКУТИЯ)', 'living_region_РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ', 'living_region_РЕСПУБЛИКА ТАТАРСТАН', 'living_region_РЕСПУБЛИКА ТЫВА', 'living_region_РЕСПУБЛИКА ХАКАСИЯ', 'living_region_РОСТОВСКАЯ ОБЛАСТЬ', 'living_region_РЯЗАНСКАЯ ОБЛАСТЬ', 'living_region_САМАРСКАЯ ОБЛАСТЬ', 'living_region_САНКТ-ПЕТЕРБУРГ', 'living_region_САРАТОВСКАЯ ОБЛАСТЬ', 'living_region_САХАЛИНСКАЯ ОБЛАСТЬ', 'living_region_СВЕРДЛОВСКАЯ ОБЛАСТЬ', 'living_region_СМОЛЕНСКАЯ ОБЛАСТЬ', 'living_region_СТАВРОПОЛЬСКИЙ КРАЙ', 'living_region_ТАМБОВСКАЯ ОБЛАСТЬ', 'living_region_ТВЕРСКАЯ ОБЛАСТЬ', 'living_region_ТОМСКАЯ ОБЛАСТЬ', 'living_region_ТУЛЬСКАЯ ОБЛАСТЬ', 'living_region_ТЮМЕНСКАЯ ОБЛАСТЬ', 'living_region_УДМУРТСКАЯ РЕСПУБЛИКА', 'living_region_УЛЬЯНОВСКАЯ ОБЛАСТЬ', 'living_region_ХАБАРОВСКИЙ КРАЙ', 'living_region_ЧЕЛЯБИНСКАЯ ОБЛАСТЬ', 'living_region_ЧУВАШСКАЯ РЕСПУБЛИКА', 'living_region_ЯРОСЛАВСКАЯ ОБЛАСТЬ', 'open_account_flg_0', 'open_account_flg_1']

In [53]:
pd.set_option('display.max_columns', 150)
train_dummies.head()

,age,credit_sum,credit_month,score_shk,monthly_income,credit_count,overdue_credit_count,tariff,paym,pti,tariff_sq,age_sq,credit_sum_sq,score_sq,income_sq,credit_month_sq,credit_count_sq,gender_F,gender_M,marital_status_CIV,marital_status_DIV,marital_status_MAR,marital_status_UNM,marital_status_WID,job_position_ATP,job_position_BIS,job_position_BIU,job_position_DIR,job_position_INP,job_position_NOR,job_position_OTHER,job_position_PNA,job_position_PNI,job_position_SPC,job_position_UMN,job_position_WOI,job_position_WRK,job_position_WRP,tariff_id_1,tariff_id_2,tariff_id_3,tariff_id_4,tariff_id_6,tariff_id_7,tariff_id_8,tariff_id_9,tariff_id_10,tariff_id_11,tariff_id_12,tariff_id_13,tariff_id_18,tariff_id_19,tariff_id_20,tariff_id_21,tariff_id_22,tariff_id_23,tariff_id_25,tariff_id_28,tariff_id_29,tariff_id_30,tariff_id_31,tariff_id_32,tariff_id_99,education_ACD,education_GRD,education_PGR,education_SCH,education_UGR,living_region_OTHER,living_region_nan,living_region_АЛТАЙСКИЙ КРАЙ,living_region_АМУРСКАЯ ОБЛАСТЬ,living_region_АРХАНГЕЛЬСКАЯ ОБЛАСТЬ,living_region_АСТРАХАНСКАЯ ОБЛАСТЬ,living_region_БЕЛГОРОДСКАЯ ОБЛАСТЬ,living_region_БРЯНСКАЯ ОБЛАСТЬ,living_region_ВЛАДИМИРСКАЯ ОБЛАСТЬ,living_region_ВОЛГОГРАДСКАЯ ОБЛАСТЬ,living_region_ВОЛОГОДСКАЯ ОБЛАСТЬ,living_region_ВОРОНЕЖСКАЯ ОБЛАСТЬ,living_region_ЕВРЕЙСКАЯ АВТОНОМНАЯ ОБЛАСТЬ,living_region_ЗАБАЙКАЛЬСКИЙ КРАЙ,living_region_ИВАНОВСКАЯ ОБЛАСТЬ,living_region_ИРКУТСКАЯ ОБЛАСТЬ,living_region_КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА,living_region_КАЛИНИНГРАДСКАЯ ОБЛАСТЬ,living_region_КАЛУЖСКАЯ ОБЛАСТЬ,living_region_КАМЧАТСКИЙ КРАЙ,living_region_КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСПУБЛИКА,living_region_КЕМЕРОВСКАЯ ОБЛАСТЬ,living_region_КИРОВСКАЯ ОБЛАСТЬ,living_region_КОСТРОМСКАЯ ОБЛАСТЬ,living_region_КРАСНОДАРСКИЙ КРАЙ,living_region_КРАСНОЯРСКИЙ КРАЙ,living_region_КУРГАНСКАЯ ОБЛАСТЬ,living_region_КУРСКАЯ ОБЛАСТЬ,living_region_ЛЕНИНГРАДСКАЯ ОБЛАСТЬ,living_region_ЛИПЕЦКАЯ ОБЛАСТЬ,living_region_МАГАДАНСКАЯ ОБЛАСТЬ,living_region_МОСКВА,living_region_МОСКОВСКАЯ ОБЛАСТЬ,living_region_МУРМАНСКАЯ ОБЛАСТЬ,living_region_НИЖЕГОРОДСКАЯ ОБЛАСТЬ,living_region_НОВГОРОДСКАЯ ОБЛАСТЬ,living_region_НОВОСИБИРСКАЯ ОБЛАСТЬ,living_region_ОМСКАЯ ОБЛАСТЬ,living_region_ОРЕНБУРГСКАЯ ОБЛАСТЬ,living_region_ОРЛОВСКАЯ ОБЛАСТЬ,living_region_ПЕНЗЕНСКАЯ ОБЛАСТЬ,living_region_ПЕРМСКИЙ КРАЙ,living_region_ПРИМОРСКИЙ КРАЙ,living_region_ПСКОВСКАЯ ОБЛАСТЬ,living_region_РЕСПУБЛИКА АДЫГЕЯ,living_region_РЕСПУБЛИКА АЛТАЙ,living_region_РЕСПУБЛИКА БАШКОРТОСТАН,living_region_РЕСПУБЛИКА БУРЯТИЯ,living_region_РЕСПУБЛИКА ДАГЕСТАН,living_region_РЕСПУБЛИКА КАЛМЫКИЯ,living_region_РЕСПУБЛИКА КАРЕЛИЯ,living_region_РЕСПУБЛИКА КОМИ,living_region_РЕСПУБЛИКА МАРИЙ ЭЛ,living_region_РЕСПУБЛИКА МОРДОВИЯ,living_region_РЕСПУБЛИКА САХА (ЯКУТИЯ),living_region_РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ,living_region_РЕСПУБЛИКА ТАТАРСТАН,living_region_РЕСПУБЛИКА ТЫВА,living_region_РЕСПУБЛИКА ХАКАСИЯ,living_region_РОСТОВСКАЯ ОБЛАСТЬ,living_region_РЯЗАНСКАЯ ОБЛАСТЬ,living_region_САМАРСКАЯ ОБЛАСТЬ,living_region_САНКТ-ПЕТЕРБУРГ,living_region_САРАТОВСКАЯ ОБЛАСТЬ,living_region_САХАЛИНСКАЯ ОБЛАСТЬ,living_region_СВЕРДЛОВСКАЯ ОБЛАСТЬ,living_region_СМОЛЕНСКАЯ ОБЛАСТЬ,living_region_СТАВРОПОЛЬСКИЙ КРАЙ,living_region_ТАМБОВСКАЯ ОБЛАСТЬ,living_region_ТВЕРСКАЯ ОБЛАСТЬ,living_region_ТОМСКАЯ ОБЛАСТЬ,living_region_ТУЛЬСКАЯ ОБЛАСТЬ,living_region_ТЮМЕНСКАЯ ОБЛАСТЬ,living_region_УДМУРТСКАЯ РЕСПУБЛИКА,living_region_УЛЬЯНОВСКАЯ ОБЛАСТЬ,living_region_ХАБАРОВСКИЙ КРАЙ,living_region_ЧЕЛЯБИНСКАЯ ОБЛАСТЬ,living_region_ЧУВАШСКАЯ РЕСПУБЛИКА,living_region_ЯРОСЛАВСКАЯ ОБЛАСТЬ,open_account_flg_0,open_account_flg_1
53397,28.000,33579.000,10,0.431,36000.000,2.000,0.000,20,3357.900,0.093,400,784.000,1127549241.000,0.186,1296000000.000,100,4.000,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
143962,38.000,23511.000,10,0.358,45000.000,2.000,0.000,19,2351.100,0.052,361,1444.000,552767121.000,0.129,2025000000.000,100,4.000,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
146922,25.000,39990.000,24,0.613,50000.000,6.000,0.000,25,1666.250,0.033,625,625.000,1599200100.000,0.376,2500000000.000,576,36.000,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
63697,65.000,3490.000,6,0.371,35000.000,4.000,0.000,18,581.667,0.017,324,4225.000,12180100.000,0.138,1225000000.000,36,16.000,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
54503,49.000,36358.000,10,0.645,50000.000,2.000,0.000,28,3635.800,0.073,784,2401.000,1321904164.000,0.416,2500000000.000,100,4.000,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0

In [54]:
# создаем обучающий и контрольный массивы значений
# зависимой переменной
y_train = train_dummies.loc[:, 'open_account_flg_1']
y_test = test_dummies.loc[:, 'open_account_flg_1']

In [55]:
# создаем обучающий и контрольный массивы 
# значений признаков
X_train = train_dummies.loc[:, 'age':'living_region_ЯРОСЛАВСКАЯ ОБЛАСТЬ']
X_test = test_dummies.loc[:, 'age':'living_region_ЯРОСЛАВСКАЯ ОБЛАСТЬ']

In [56]:
# импортируем класс RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
# создаем экземпляр класса RandomForestClassifier
forest=RandomForestClassifier(n_estimators=800, max_depth=17, random_state=152, n_jobs=-1)
# подгоняем модель
forest.fit(X_train, y_train)
# импортируем функцию roc_auc_score
from sklearn.metrics import roc_auc_score
# оцениваем дискриминирующую способность 
# модели случайного леса
print("AUC на обучающей выборке: {:.3f}".
      format(roc_auc_score(y_train, forest.predict_proba(X_train)[:, 1])))
print("AUC на контрольной выборке: {:.3f}".
      format(roc_auc_score(y_test, forest.predict_proba(X_test)[:, 1])))

AUC на обучающей выборке: 0.896
AUC на контрольной выборке: 0.766

In [57]:
# импортируем класс LogisticRegression
from sklearn.linear_model import LogisticRegression
# создаем экземпляр класса LogisticRegression
# и подгоняем модель
logreg = LogisticRegression().fit(X_train, y_train)
# оцениваем дискриминирующую способность 
# модели логистической регрессии
print("AUC на обучающей выборке: {:.3f}".
      format(roc_auc_score(y_train, logreg.predict_proba(X_train)[:, 1])))
print("AUC на контрольной выборке: {:.3f}".
      format(roc_auc_score(y_test, logreg.predict_proba(X_test)[:, 1])))

AUC на обучающей выборке: 0.546
AUC на контрольной выборке: 0.545

In [58]:
# импортируем класс StandardScaler
from sklearn.preprocessing import StandardScaler
# создаем экземпляр класса StandardScaler
scaler = StandardScaler()

In [59]:
# подгоняем модель
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [60]:
# преобразовываем данные
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [61]:
# строим модель логистической регрессии на данных,
# отмасштабированных с помощью StandardScaler
logreg = LogisticRegression().fit(X_train_scaled, y_train)
print("AUC на обучающей выборке: {:.3f}".
      format(roc_auc_score(y_train, logreg.predict_proba(X_train_scaled)[:, 1])))
print("AUC на контрольной выборке: {:.3f}".
      format(roc_auc_score(y_test, logreg.predict_proba(X_test_scaled)[:, 1])))

AUC на обучающей выборке: 0.726
AUC на контрольной выборке: 0.728

In [62]:
# применяем MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
scaler2 = MinMaxScaler()
scaler2.fit(X_train)
X_train_scaled2 = scaler2.transform(X_train)
X_test_scaled2 = scaler2.transform(X_test)

In [63]:
# строим модель логистической регрессии на данных,
# отмасштабированных с помощью MinMaxScaler
logreg = LogisticRegression().fit(X_train_scaled2, y_train)
print("AUC на обучающей выборке: {:.3f}".
      format(roc_auc_score(y_train, logreg.predict_proba(X_train_scaled2)[:, 1])))
print("AUC на контрольной выборке: {:.3f}".
      format(roc_auc_score(y_test, logreg.predict_proba(X_test_scaled2)[:, 1])))

AUC на обучающей выборке: 0.725
AUC на контрольной выборке: 0.727

In [64]:
from sklearn.preprocessing import RobustScaler
scaler3 = RobustScaler()
scaler3.fit(X_train)
X_train_scaled3 = scaler3.transform(X_train)
X_test_scaled3 = scaler3.transform(X_test)

In [65]:
logreg = LogisticRegression().fit(X_train_scaled3, y_train)
print("AUC на обучающей выборке: {:.3f}".
      format(roc_auc_score(y_train, logreg.predict_proba(X_train_scaled3)[:, 1])))
print("AUC на контрольной выборке: {:.3f}".
      format(roc_auc_score(y_test, logreg.predict_proba(X_test_scaled3)[:, 1])))

AUC на обучающей выборке: 0.726
AUC на контрольной выборке: 0.728